services:
  - type: web
    name: demo-feedback
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 24
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_BUCKET
        sync: false
      - key: SUPABASE_PUBLIC_URL
        sync: false
